### ISSUE TITLE
Salesforce has disabled TLS 1.0

### ISSUE THREAD

**Issue by derekforeman** [michael-shattuck/SalesforceMagic#26]
Now that Salesforce has disabled TLS 1.0 should 

ServicePointManager.SecurityProtocol be set to 1.1 or greater by default? Perhaps in the SalesforceClient object.

**Comment by michael-shattuck** [comment]
It might be a good idea to make this configurable actually.

**Comment by michael-shattuck** [comment]
This was resolved in the last pull request
